### ISSUE TITLE
[BUG] Dropdown not working on mobile

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/LinkFree#2333]
### Description

![image](https://user-images.githubusercontent.com/30869493/206142539-0a8efb4e-d0af-4c9c-b543-28915464857d.png)

Dropdown to milestones, etc is not working

### Screenshots

![image](https://user-images.githubusercontent.com/30869493/206142437-3ce398b5-56f5-4c18-ae81-a7a52ff17b51.png)
```shell
6framework-ffee79c6390da51e.js:9 
        
       Uncaught TypeError: e.preventDefault is not a function
    at changeTab ([username]-7552eba5cda64c76.js:1:10158)
    at onChange ([username]-7552eba5cda64c76.js:1:10648)
    at Object.Nb (framework-ffee79c6390da51e.js:9:15047)
    at Tb (framework-ffee79c6390da51e.js:9:15201)
    at framework-ffee79c6390da51e.js:9:33544
    at nf (framework-ffee79c6390da51e.js:9:33643)
    at se (framework-ffee79c6390da51e.js:9:34057)
    at framework-ffee79c6390da51e.js:9:39557
    at Rk (framework-ffee79c6390da51e.js:9:96494)
    at Jb (framework-ffee79c6390da51e.js:9:14179)
```

### Additional information

n/a

**Comment by simonefranconetti** [comment]
Hi @schmelto ! I'd like to work on this bug. Can you assign it to me?
