### ISSUE TITLE
Prettier fails

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2404]
### Description

Prettier fails to format json file and commit it back, I think this is making it harder for people, and it should be helping

https://github.com/EddieHubCommunity/LinkFree/actions/runs/3700762171/jobs/6275926075

```
error: Your local changes to the following files would be overwritten by checkout:
[32](https://github.com/EddieHubCommunity/LinkFree/actions/runs/3700762171/jobs/6275926075#step:6:33)
	data/Saurav-Pant.json
[33](https://github.com/EddieHubCommunity/LinkFree/actions/runs/3700762171/jobs/6275926075#step:6:34)
Please commit your changes or stash them before you switch branches.
[34](https://github.com/EddieHubCommunity/LinkFree/actions/runs/3700762171/jobs/6275926075#step:6:35)
Aborting
[35](https://github.com/EddieHubCommunity/LinkFree/actions/runs/3700762171/jobs/6275926075#step:6:36)
Error: Invalid status code: 1
[36](https://github.com/EddieHubCommunity/LinkFree/actions/runs/3700762171/jobs/6275926075#step:6:37)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
[37](https://github.com/EddieHubCommunity/LinkFree/actions/runs/3700762171/jobs/6275926075#step:6:38)
    at ChildProcess.emit (node:events:390:28)
[38](https://github.com/EddieHubCommunity/LinkFree/actions/runs/3700762171/jobs/6275926075#step:6:39)
    at maybeClose (node:internal/child_process:1064:16)
[39](https://github.com/EddieHubCommunity/LinkFree/actions/runs/3700762171/jobs/6275926075#step:6:40)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
[40](https://github.com/EddieHubCommunity/LinkFree/actions/runs/3700762171/jobs/6275926075#step:6:41)
  code: 1
[41](https://github.com/EddieHubCommunity/LinkFree/actions/runs/3700762171/jobs/6275926075#step:6:42)
}
[42](https://github.com/EddieHubCommunity/LinkFree/actions/runs/3700762171/jobs/6275926075#step:6:43)
Error: Invalid status code: 1
[43](https://github.com/EddieHubCommunity/LinkFree/actions/runs/3700762171/jobs/6275926075#step:6:44)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
[44](https://github.com/EddieHubCommunity/LinkFree/actions/runs/3700762171/jobs/6275926075#step:6:45)
    at ChildProcess.emit (node:events:390:28)
[45](https://github.com/EddieHubCommunity/LinkFree/actions/runs/3700762171/jobs/6275926075#step:6:46)
    at maybeClose (node:internal/child_process:1064:16)
[46](https://github.com/EddieHubCommunity/LinkFree/actions/runs/3700762171/jobs/6275926075#step:6:47)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

**Comment by eddiejaoude** [comment]
Thank you Dan 👍 

> are the people seeing this creating their json file on GitHub directly or pushing from their computer?

I think people are using GitHub directly, which is great, but then the formatting is not always correct

Q. Could we be more flexible with the formatting, as long as it is valid, then Prettier can fix it once merged - I know not ideal as it will effectively deploy twice (or we could run Prettier on a cron on the `main` branch)

**Comment by dan-mba** [comment]
> Q. Could we be more flexible with the formatting, as long as it is valid, then Prettier can fix it once merged - I know not ideal as it will effectively deploy twice (or we could run Prettier on a cron on the `main` branch)

I think replacing prettier with a [JSON checker](https://github.com/limitusus/json-syntax-check) in the action for a PR would work. 
It might makes sense to only run prettier when creating a release.

**Comment by eddiejaoude** [comment]
I think I might have fixed it with `skip_checkout: true` option on Prettier GitHub Action

https://github.com/EddieHubCommunity/LinkFree/pull/2409/commits

**Comment by dan-mba** [comment]
While the commit worked, the action still failed.
https://github.com/EddieHubCommunity/LinkFree/actions/runs/3706099976/jobs/6280875846

I think I found some documentation in the [git-auto-commit-action Readme](https://github.com/stefanzweifel/git-auto-commit-action#workflow-should-run-in-base-repository) changes that need to be made to make it work

**Comment by eddiejaoude** [comment]
Yep the Action failed for the commit that has bad formatting, but it looks like it passed after Prettier ran and made the 2nd commit?

<img width="362" alt="Screenshot 2022-12-15 at 18 49 16" src="https://user-images.githubusercontent.com/624760/207942962-a4d918a1-8423-4f45-ae59-8f8757bc7e38.png">

**Comment by dan-mba** [comment]
If you look at the [format action logs](https://github.com/EddieHubCommunity/LinkFree/actions/workflows/prettier.yml) It only ran once.
I think commits from an action won't trigger the same action to re-run.

**Comment by eddiejaoude** [comment]
> I think commits from an action won't trigger the same action to re-run.

yes I think you are correct 👍

**Comment by eddiejaoude** [comment]
Just thinking about it, won't the GitHub Action run in their fork, so it should be able to write to their branch

I am testing it now in my for and it keeps writing but in my fork which updates the pull request

**Comment by eddiejaoude** [comment]
Oh it is because the token in the environment variable is from my account 😂 `secrets.GH_PAT`

I wonder if I change this back to `secrets.GITHUB_TOKEN`

**Comment by dan-mba** [comment]
Do you have a test account that doesn't have write access to the main LinkFree repo? If so, try testing with a fork on that account. I think some of your tests are working because your account has write access to both the fork and upstream repo.

**Comment by eddiejaoude** [comment]
oh good point, yes I do, I will try that, thank you Dan 👍

**Comment by eddiejaoude** [comment]
Ok I learnt something new, by default on forks the GitHub Actions don't run... (this is my test account with no Org/Repo permissions)

<img width="1273" alt="Screenshot 2022-12-17 at 13 01 27" src="https://user-images.githubusercontent.com/624760/208243126-775ac7d4-d833-4969-8864-c9bd700ca570.png">

**Comment by eddiejaoude** [comment]
1. PR from fork (no permissions given) with situation:

- valid json
- invalid formatting

note: linting passes with new `json-check` GH Action and Prettier does not run

```json
{
  "name": "Eddie Jaoude Test profile",
  "type": "personal",
  "bio": "This is my profile where I test stuff","avatar": "https://github.com/eddiejaoude2.png",
  "links": [
    {
      "name": "Eddie Jaoude Official LinkFree profile",
      "url": "https://linkfree.eddiehub.io/eddiejaoude",
      "icon": "link"
    }
  ]
}
```

<img width="956" alt="Screenshot 2022-12-17 at 13 04 39" src="https://user-images.githubusercontent.com/624760/208243243-d09f87b8-4a85-43eb-845a-8d966c6fa1ca.png">

2. Merge PR Prettier ran and fixed formatting https://github.com/EddieHubCommunity/LinkFree/commit/74173eeb379716c1091acbfa2991f7147e959c99

<img width="1655" alt="Screenshot 2022-12-17 at 13 11 11" src="https://user-images.githubusercontent.com/624760/208243547-6e7a7d9a-bf9d-4850-b65e-4b1e629f7a93.png">
