### ISSUE TITLE
500: Internal Server Error on https://linkfree.io/events

### ISSUE THREAD

**Issue by sansarmaske** [EddieHubCommunity/LinkFree#6169]
### Description

I am getting "500: Internal Server Error" when accessing  [linkfree.io/events](https://linkfree.io/events)

### Screenshots

![Screenshot 2023-04-18 130507](https://user-images.githubusercontent.com/18899162/232701895-dd61f681-ee87-463a-aeea-ca1a6232d567.jpg)

### Additional information
Following is the error shown on console:
```javascript
 RangeError: Invalid time value
    at c (104-ac6ebdc6f81c2b76.js:1:6921)
    at ab (framework-ce84985cd166733a.js:9:60917)
    at i (framework-ce84985cd166733a.js:9:119475)
    at oO (framework-ce84985cd166733a.js:9:99114)
    at framework-ce84985cd166733a.js:9:98981
    at oF (framework-ce84985cd166733a.js:9:98988)
    at ox (framework-ce84985cd166733a.js:9:95740)
    at oS (framework-ce84985cd166733a.js:9:94295)
    at x (framework-ce84985cd166733a.js:33:1373)
    at MessagePort.T (framework-ce84985cd166733a.js:33:1903)
```

_No response_

**Comment by sansarmaske** [comment]
Fixed by #6171
